# Generated by Django 4.1 on 2022-08-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0002_remove_locationmodel_id_locationmodel_id_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timemodel',
            old_name='Concert_name',
            new_name='concert_name',
        ),
        migrations.AddField(
            model_name='timemodel',
            name='status',
            field=models.IntegerField(choices=[('start_s', 'فروش بلیط شروع شده است'), ('end_s', 'فروش بلیط تمام شده است!'), ('cancel_s', 'این سانس کنسل شده است'), ('sales_s', 'در حال فروش بلیط')], default=0),
            preserve_default=False,
        ),
    ]
