# Generated by Django 4.1 on 2022-08-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0003_rename_concert_name_timemodel_concert_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('gender', models.IntegerField(choices=[('Male', 'مرد'), ('Female', 'زن')])),
            ],
        ),
        migrations.AddField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='poster_pics'),
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField()),
                ('ticket_pic', models.ImageField(blank=True, upload_to='ticket_pics')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel')),
            ],
        ),
    ]
