# Generated by Django 4.1 on 2022-08-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0004_profilemodel_concertmodel_poster_ticketmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name_plural': 'کنسرت ها'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name_plural': 'محل برگزاری'},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'verbose_name_plural': 'بلیط'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name_plural': 'سانس'},
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='lenght',
            field=models.IntegerField(verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='poster',
            field=models.ImageField(null=True, upload_to='poster_pics', verbose_name='عکس پوستر'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='singer_name',
            field=models.CharField(max_length=100, verbose_name='نام خواننده'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='address',
            field=models.CharField(max_length=500, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='id_number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد محل'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام محل'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='family',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.IntegerField(choices=[('male', 'مرد'), ('female', 'زن')], verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics', verbose_name='عکس نمایه'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_number',
            field=models.IntegerField(verbose_name='شماره بلیط'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_pic',
            field=models.ImageField(blank=True, upload_to='ticket_pics', verbose_name='عکس بلیط'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel', verbose_name='سانس'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='concert_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.concertmodel', verbose_name='کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='location_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.locationmodel', verbose_name='محل برگزاری'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='seats',
            field=models.IntegerField(verbose_name='تعداد صندلی'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='start_date_time',
            field=models.DateTimeField(verbose_name='تاریخ و ساعت برگزاری'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='status',
            field=models.IntegerField(choices=[('start_s', 'فروش بلیط شروع شده است'), ('end_s', 'فروش بلیط تمام شده است!'), ('cancel_s', 'این سانس کنسل شده است'), ('sales_s', 'در حال فروش بلیط')], verbose_name='وضعیت'),
        ),
    ]
