# Generated by Django 4.1 on 2022-08-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0007_alter_profilemodel_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timemodel',
            old_name='concert_name',
            new_name='concert_model',
        ),
        migrations.RenameField(
            model_name='timemodel',
            old_name='location_name',
            new_name='location_model',
        ),
    ]
