# Generated by Django 4.1 on 2022-08-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ticketSales', '0008_rename_concert_name_timemodel_concert_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profilemodel', verbose_name='کاربر'),
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
